version: '3'

services:
  vocaboost:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      # Add other environment variables here if needed, e.g.:
      # - ORIGIN=http://localhost:3000
    restart: unless-stopped
    volumes:
      - ~/vocaboost_sync:/root/vocaboost_sync
