version: '3'

services:
  vocaboost:
    build: .
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - BODY_SIZE_LIMIT=1G
      - ORIGIN=https://wizcoding.com
    restart: unless-stopped
    volumes:
      - ~/vocaboost_sync:/root/vocaboost_sync

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - vocaboost
    restart: unless-stopped
